// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-i6hl5bJv6bs6REAyl8gAH7XiW4joHWU',
    appId: '1:469911106051:web:20778def05deff31795436',
    messagingSenderId: '469911106051',
    projectId: 'loveecounter-a578a',
    authDomain: 'loveecounter-a578a.firebaseapp.com',
    storageBucket: 'loveecounter-a578a.firebasestorage.app',
    measurementId: 'G-KKQ7HT52RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO4LlHXMJxjy0CNSPncVqomL_q3Uc_7PY',
    appId: '1:469911106051:android:b0537fbee33bfa81795436',
    messagingSenderId: '469911106051',
    projectId: 'loveecounter-a578a',
    storageBucket: 'loveecounter-a578a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6lRDp8V8tqbU3cF7jeE5WM9cXyJqU-OM',
    appId: '1:469911106051:ios:2285d0da915f9fcf795436',
    messagingSenderId: '469911106051',
    projectId: 'loveecounter-a578a',
    storageBucket: 'loveecounter-a578a.firebasestorage.app',
    iosBundleId: 'com.example.loveEcounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6lRDp8V8tqbU3cF7jeE5WM9cXyJqU-OM',
    appId: '1:469911106051:ios:2285d0da915f9fcf795436',
    messagingSenderId: '469911106051',
    projectId: 'loveecounter-a578a',
    storageBucket: 'loveecounter-a578a.firebasestorage.app',
    iosBundleId: 'com.example.loveEcounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-i6hl5bJv6bs6REAyl8gAH7XiW4joHWU',
    appId: '1:469911106051:web:d3072038eb5afeb4795436',
    messagingSenderId: '469911106051',
    projectId: 'loveecounter-a578a',
    authDomain: 'loveecounter-a578a.firebaseapp.com',
    storageBucket: 'loveecounter-a578a.firebasestorage.app',
    measurementId: 'G-EKFSCWYFPY',
  );
}
